default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: events_app_development

test:
  <<: *default
  database: events_app_test

production:
  <<: *default
  database: events_app_production
  url: <%= ENV['DATABASE_URL'] %>
